class EmptyResultWarning(Warning): ...


class GeometryNotCoveredWarning(Warning): ...


class GeometryNotCoveredError(Exception): ...


class InvalidGeometryFilter(Exception): ...


class MultiprocessingRuntimeError(RuntimeError): ...


class QueryNotGeocodedError(ValueError): ...
